### PR TITLE
Exploring Content Delivery Network 

### LINKED ISSUE #12: Exploring Content Delivery Network
**MicroByte Title:** Exploring Content Delivery Network

**Domain:** System Design

**Scope of learning for learners:** Learners will identify the skills of Chrome Developer Tools, explore the CDN of facebook around the globe, re-direct to System Design ME for practical CDN.

**Activities:** 
1. Setup Tools
2. Extracting CDN server IPs from a Facebook video.
3.  Digging up approximate locations of the CDN servers.
4. Showcase your results
5. Hand's On with CDN
6. Mega Challenge

### PR DESCRIPTION
**Pull request by jain-yakshit-1**
An important topic of Content Delivery Network to serve content across the globe.

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by Kevinpaulose05 — APPROVED** [review]
Amzing work @jnana-cetana again. I like how u used crio MEs to develop ur own microbyte using it. 
A couple of minute things I felt if u cud add it would be better:
1. Give the link of BrowSec VPN 
2. In activity 2 point 5, the answer given is a bit absurd. Just give the right answer(no need to show both options).
3. In activity 5 provide the link of SD ME

All these will make it more appealing in my opinion. Again needless to say:
1. Open issues for learners(preferably)
2. Showcase ur microbyte

**Comment by jain-yakshit-1** [comment]
I need to correct some grammatical errors
And regarding the Learners issue
I have 3 of them in my mind.
I will create it immediately once it gets merged

**Comment by YourAKShaw** [comment]
@jnana-cetana Kindly make the necessary changes as mentioned by @Kevinpaulose05 and you'll have my approval.

**Comment by jain-yakshit-1** [comment]
Yeah @Ak-Shaw . I will improve the quality of byte as per the suggestions from @Kevinpaulose05

**Review by YourAKShaw — APPROVED** [review]
@jnana-cetana Yet another premium contribution! :100: 

The way you curated the content, it's quite engaging and also I've had my fun reviewing it. It was enough to make me a learner of your content in terms for a better review. And the meme was hysterical! :rofl: 

As per your request, we'll wait for another approval from @amoghrajesh before merging this PR to ensure the quality of your contribution.

Keep contributing! :heart_decoration:

**Review by sudhanshutiwari264 — APPROVED** [review]
@jnana-cetana great work again !🎉

**Review by amoghrajesh — APPROVED** [review]
Hey @jnana-cetana!
This is absolutely premium content. I have zero complaints about this one.
Just one question - In activity 2 point 5, are the two options supposed to be checkboxes or radio buttons? If yes, they are not functional 🤔 

I absolutely loved the activity 4 hint!
Great work again! Really happy to be getting to review such amazing content.
Keep contributing to the community. 
Once this gets merged, start to think of some learner issues and you must already be aware of the showcasing.

Thanks!

**Comment by amoghrajesh** [comment]
@jnana-cetana thanks for contributing!
Kindly showcase your contribution to others using [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) template.

**Comment by jain-yakshit-1** [comment]
Thanks @amoghrajesh . I hope you enjoyed reviewing the content.
In activity 2 point 5, I have just listed the options as a part of result. The checkboxes are not suppose to work.

**Pull request merged**
