### PR TITLE
 AWS High Availability Architecture

### LINKED ISSUE #23: AWS High Availability Architecture
**MicroByte Title:**  AWS High Availability Architecture

**Domain:**  Web Service

**Scope of learning for learners:**  
- Learner will be able to deploy a website with `High availability`, `secure`  website, and make website `manageable`.

**Activities:** 
- Activity 1 (Launched an instance in AWS): launched an instance in AWS using AWS CLI and this activity contain task for the learner.
- Activity 2 (Configured Webserver): configured Webserver by installing Apache Webserver and this activity contain task for the learner.
- Activity 3 (Created an EBS Volume): created EBS Volume using AWS CLI.
- Activity 4 (Attach EBS Volume to Instance): attached EBS Volume to the instance using AWS CLI and this activity contain task for the learner.
- Activity 5 (Created and Formated a Partition): created a Partition in Linux instance and then format the partition.
- Activity 6 (Mounted /var/www/html directory to partition): mounted  /var/www/html directory to the partition and created a HTML Page and this activity contain task for the learner.
- Activity 7 (Created S3 Bucket): created S3 bucket using AWS CLI.
- Activity 8 (Uploaded images in S3 Bucket):Uploaded images in S3 bucket and copy the URL of images and pasted in webpage.
- Activity 9(Created Cloudfront Distribution ): Created Cloudfront Distribution using AWS CLI and this activity contain task for the learner.

### PR DESCRIPTION
**Pull request by Nitesh-thapliyal**
### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @Nitesh-thapliyal!
You have made most of the changes requested by me, but you might have missed out a few so I am gonna reiterate it for you:

1. In Prerequisites, you are assuming that it is a Windows user. What if he uses Linux/Mac? Provide links for these too.
2. You still have not mentioned what you need in the HTML in activity 7. Tell the learner how big the html should be (Just a simple boilerplate or does it need to have anything)
3. You got rid of the part in the previous version when you were launching the website in terms of activity 11 (Add that part but in Activity 10).

Apart from all these changes, very good work, man. 
Makes these changes as soon as possible.

**Comment by Kevinpaulose05** [comment]
@Nitesh-thapliyal Pls let us know when it is ready :)

**Comment by amoghrajesh** [comment]
Hey, @Nitesh-thapliyal I think you have broken some structure here, I can't reach your files due to it being in `unknown repository`. See the highlight in the screenshot below and kindly fix this asap.
Ping me or @Kevinpaulose05 if you need any sort of help.

image

**Comment by amoghrajesh** [comment]
Everyone - Check out PR #25

**Pull request closed without merging**
