### PR TITLE
Add Crio-Byte for System Design Load Balancer

### LINKED ISSUE #4: Traffic Cop - Learn Load Balancer using HAProxy
**MicroByte Title:** Traffic Cop - Learn Load Balancer using HAProxy

**Domain:** System Design, Networking

**Scope of learning for learners:** Learners will get an idea of how the systems in the real world are made scalable and handle millions of requests by routing the requests to various machines in the cluster using Load Balancer.

**Activities:** The MicroByte activities will start with 1) Experience real-world load balancer of google.com
2) Installation of HA-proxy
3) Launch server applications with different ports.
4)  Configure HA-Proxy to load balance server with different load balancing strategies.

### PR DESCRIPTION
**Pull request by jain-yakshit-1**
An important topic of load balancer to design any distributed system application in the real world.
## Closes #4 

<Put a x between the square brackets. Make sure you get them all>

### Checklist: 

- [x] Added activities for learners
- [x] Didn't give the solutions to the added activities straight away
- [x] Followed a LearnByDoing approach
- [x] Clean and well documented code (if source code files are involved)
- [x] Added images for better understanding if deemed necessary

### CODE REVIEW

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @jnana-cetana !
This is really good content and something that usually people won't think of.
I really like the way you have put together all the information.

I have to suggest some changes to make it better:

1. In 'prerequisite' section, you have provided the installation instructions in step 1 for haproxy, dnsutils, and flask. I suggest you make the dnsutils and flask installation instructions as todos. What I mean by this is that don't give out commands for these two. Just provide a Incommand for haproxy.
2. In Activity 2, you have given out exact command `python3 app.py 8080`. No need of this because anyways you provided the command prototype just above it 😄 
3. In Activity 3.4, don't provide the command for `check` command. The learner should be curious to search and find it out :)
4. You can cut down some content in Activity 4 I think length wise.

Apart from these small changes, amazing content man. 
Really impressed with the amount of activities it carries 😄 
Make these changes and we shall re review it asap

**Comment by jain-yakshit-1** [comment]
Changes made as per the suggestion @amoghrajesh

**Review by YourAKShaw — APPROVED** [review]
@jnana-cetana Awesome work! This is some premium content you have for us. Let's see what the other reviewers say. My word, I liked the way you laid out the content and the friendly tone you used throughout. 

Looking forward to more contributions from you! :heart_decoration:

**Comment by jain-yakshit-1** [comment]
Thanks @Ak-Shaw . More Micro-bytes on the way.

**Review by Kevinpaulose05 — APPROVED** [review]
This is pretty awesome. Good topic + perfect execution.  With the background you are from this was expected and u have delivered it beautifully.  Two things to do now(these are from my side):
1. Open issues for learners. Follow the right format. From what I see there is very little scope(i maybe wrong :p). 
2. Showcase ur microbyte ONLY after we merge it.

Don't stop here yet. Keep contributing like these as much as you can.

Happy Contributing!!

**Review by amoghrajesh — APPROVED** [review]
Hi @jnana-cetana!
I am really impressed with the changes you have made. This is some really good content.
To be honest, taking a topic so subtle and pulling off something like this isn't easy.
Kudos man. 
Approving it!
Meanwhile until your PR gets reviewed by other reviewers try to think of some smaller learner issues too, I see you have a mega challenge but still 😄

**Comment by jain-yakshit-1** [comment]
Thanks @amoghrajesh , @Ak-Shaw , @CrioDo . You all are awesome

**Comment by amoghrajesh** [comment]
@jnana-cetana Kindly showcase your MicroByte in the #microbyte-showcase channel on slack using [this](https://github.com/Crio-Bytes/Demo-Repo/blob/master/Maintainer%20Resources/new-microbyte-showcase-template.md) template.

**Comment by amoghrajesh** [comment]
@all-contributors kindly add @jnana-cetana for:

- [x] code
- [x] content
- [x] doc
- [x] ideas

**Pull request merged**
