### PR TITLE
update readme with MicroByte info

### PR DESCRIPTION
**Pull request by YourAKShaw**
Have laid out a nice way to represent the merged MicroBytes in the README of the repo.

If the aforementioned pattern gets approved and this PR gets merged, similar changes will be taken under for all the other respective master repos.

Kindly only merge this PR after the approval of all the assigned reviewers.

### CODE REVIEW

**Review by amoghrajesh — CHANGES_REQUESTED** [review]
Hey @Ak-Shaw!
I personally like this idea of putting the MBs in a showcase manner.
From my end, a few changes should make it better:
1. The description is 2 - 3 para long for each MB, we can cut it down to just one paragraph because as more MBs come, it will make the readme gargantuan.
2. Along with the name of the contributor, probably add his/her GitHub username too 😄 

Let's see what others gotta say 👍🏽

**Review by sudhanshutiwari264 — COMMENTED** [review]
@Ak-Shaw I also liked your creativity and hope you make the requested changes suggested by @amoghrajesh !
Overall it's 🤩
Let's wait wht others say !

**Comment by YourAKShaw** [comment]
Kindly check it out if you guys need any more changes.

**Review by amoghrajesh — APPROVED** [review]
Yes @Ak-Shaw this is exactly as I expected it to be. 
Go ahead and implement it 😄

**Pull request merged**
